// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yekldqzhalupoudrlems.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlla2xkcXpoYWx1cG91ZHJsZW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mjc0MjgsImV4cCI6MjA3MDQwMzQyOH0.DaKZF9x_FdvUuG5LBUku_-OC84twwFW8-nRrekjSj9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});